# Name of the track
name = "Background Grooves"

# List of instructions
[[instructions]]
    # This grabs the 50 most recent liked songs by the user and selects 20 of those by random
    type = "saved_tracks"
    sample = 50
    amount = 20
    randomize = true

[[instructions]]
    # Gets the user's top artists
    type = "user_top_artists"
    # Can be 'short' 'medium' or 'long'
    term = "short"
    limit = 3
    [instructions.instruction]
        # Gets each artists top 5 tracks
        type = "artist_top_tracks"
        amount = 5

[[instructions]]
    # Gets the user's top 20 tracks (by listen)
    type = "user_top_tracks"
    term = 'short'
    amount = 20

[[instructions]]
    # Gets recommendations for specific artists/songs
    # All this stuff is supported https://developer.spotify.com/documentation/web-api/reference/#/operations/get-recommendations
    type = "recommendations"
    artists = ["SANOVA", "fox capture plan"]

    # For recommendation tracks you can add a full instruction
    tracks = { type = "random", select = 1, instruction = { type = "artist_top_tracks", artist = "fox capture plan"} }

    # You can fine tune exactly what you want
    max_speechiness = 0.3
    limit = 50
    max_energy = 0.7

[[instructions]]
    # You can also add genres https://developer.spotify.com/console/get-available-genre-seeds/
    type = "recommendations"
    artists = ["insaneintherainmusic", "All That Jazz"]
    max_speechiness = 0.1
    limit = 50
    max_energy = 0.6

[[instructions]]
    # Gets related artists to a specific artist
    type = 'related_artists'
    artist = 'fox capture plan'
    amount = 5
    [instructions.instruction]
        # Grab top 3 tracks from each
        type = "artist_top_tracks"
        amount = 3

[[instructions]]
    type = 'related_artists'
    artist = 'SANOVA'
    amount = 5
    [instructions.instruction]
        type = "artist_top_tracks"
        amount = 3

[[instructions]]
    # Clears duplicate tracks
    type = 'clear_duplicates'

[[instructions]]
    # Clears tracks before a specific date. In my case I want more modern songs. Especially modern jazz.
    type = 'clear_before'
    max_date = '1985-01-01'

[[instructions]]
    type = "artist_tracks"
    artist = "fox capture plan"
    fetch = 100
    select = 25

[[instructions]]
    type = "artist_tracks"
    artist = "insaneintherainmusic"
    fetch = 100
    select = 30