clear_duplicates = true
region = 'US'

# These are from my wake up playlist
remove_artists = ['Tracy Island', 'melodysheep']

[audio_sort]
    method = 'traveling'

[upload]
    name = 'My Current Bops with Spice'

[[instructions]]
    type = "playlist_tracks"
    name = 'My Current Bops'

[[instructions]]
    type = "generate"
    tracks = {type = "playlist_tracks", name = "My Current Bops"}
    amount = 80
