clear_duplicates = true
region = 'US'

# These are from my wake up playlist
remove_artists = ['Tracy Island', 'melodysheep']

[audio_sort]
    method = 'traveling'

[upload]
    name = 'My Current Bops'

[[instructions]]
    type = "top_tracks"
    term = 'short'
    amount = 50

[[instructions]]
    type = "top_tracks"
    term = 'medium'
    amount = 10

[[instructions]]
    type = "playlist_tracks"
    name = "Saved: Bops"
