clear_duplicates = true
region = 'US'

# These are from my wake up playlist
remove_artists = ['Tracy Island', 'melodysheep']

[similar]
    tracks = {type = "playlist_tracks", name = 'My Current Bops'}

[upload]
    name = 'My Current Bops with Spice'

[[instructions]]
    type = "generate"
    tracks = {type = "playlist_tracks", name = "My Current Bops"}
    amount = 80
