name = 'My Current Bops'
daily = true
clear_duplicates = true

[[instructions]]
    type = "saved_tracks"
    amount = 30
    randomize = false

[[instructions]]
    type = "top_tracks"
    term = 'short'
    amount = 50

[[instructions]]
    type = "top_tracks"
    term = 'medium'
    amount = 10
