[separate]
    title = 'Mix {0}'
    instruction = {type = "generate", amount=50, mix_same=true, pool_size=20}
    [separate.clear_duplicates]
        active = true
    [separate.random]
        active = true


[[instructions]]
    type = "top_tracks"
    term = 'short'
    amount = 50

[[instructions]]
    type = "top_tracks"
    term = 'medium'
    amount = 20
