clear_duplicates = true
region = 'US'

[upload]
    name = 'My Current Bops'

[[instructions]]
    type = "saved_tracks"
    amount = 30
    randomize = false

[[instructions]]
    type = "top_tracks"
    term = 'short'
    amount = 50

[[instructions]]
    type = "top_tracks"
    term = 'medium'
    amount = 10
