clear_duplicates = true
region = 'US'
explicit = false

[audio_sort]
    method = 'traveling'
    chunks = 25
    random_offset = true

[upload]
    name = "Gaming Watch"

[[instructions]]
    type = "generate"
    tracks = {type = "playlist_tracks", name = "Gamer Mode"}
    amount = 100