clear_duplicates = true
region = 'US'
explicit = false

[upload]
    name = "Grooving"

[[instructions]]
    type = "playlist_tracks"
    name = "Saved: Bops"

[[instructions]]
    type = "generate"
    tracks = {type = "playlist_tracks", name = "Saved: Bops"}
    amount = 50

[[instructions]]
    type = "recommendations"
    artists = ["fox capture plan", "PRIMITIVE ART ORCHESTRA", "SANOVA"]

    max_speechiness = 0.3
    limit = 70
    max_energy = 0.7

[[instructions]]
    type = "recommendations"
    artists = ["jizue", "insaneintherainmusic"]

    tracks = { type = "saved_tracks", amount = 1, artist = "jizue" }

    max_speechiness = 0.5
    limit = 30
    max_energy = 0.7
