# Name of the track
name = "Grooving"
daily = true

[[instructions]]
    type = "playlist"
    name = "Saved: Bops"

[[instructions]]
    type = "recommendations"
    artists = ["SANOVA"]

    tracks = { type = "saved_tracks", amount = 1, artist = "SANOVA" }

    max_speechiness = 0.3
    limit = 30
    max_energy = 0.7

[[instructions]]
    type = "recommendations"
    artists = ["fox capture plan"]

    tracks = { type = "saved_tracks", amount = 1, artist = "fox capture plan" }

    max_speechiness = 0.3
    limit = 30
    max_energy = 0.7

[[instructions]]
    type = "recommendations"
    artists = ["PRIMITIVE ART ORCHESTRA"]

    tracks = { type = "saved_tracks", amount = 1, artist = "PRIMITIVE ART ORCHESTRA" }

    max_speechiness = 0.3
    limit = 15
    max_energy = 0.7

[[instructions]]
    type = "recommendations"
    artists = ["jizue"]

    tracks = { type = "saved_tracks", amount = 1, artist = "jizue" }

    max_speechiness = 0.5
    limit = 15
    max_energy = 0.7

[[instructions]]
    type = "recommendations"
    artists = ["Siena Wind Orchestra"]

    max_speechiness = 0.5
    limit = 15
    max_energy = 0.7
    min_energy = 0.4

[[instructions]]
    # Clears duplicate tracks
    type = 'clear_duplicates'
