clear_duplicates = true
region = 'US'
explicit = false

random = true

[upload]
    name = "Math but Chill"

[energy]
    lower = 0
    upper = 0.5

[[instructions]]
    type = "recommendations"
    artists = ["spotify:artist:1v7B6ZWa7QRQS3knn3Jvf4", "spotify:artist:1v7B6ZWa7QRQS3knn3Jvf4"]

    min_instrumentalness = 0.5
    limit = 50
    pool_size = 100
    max_energy = 0.6
    min_acousticness = 0.5

[[instructions]]
    type = "artist_top"
    artist = "spotify:artist:1v7B6ZWa7QRQS3knn3Jvf4"

[[instructions]]
    type = "artist_top"
    artist = "spotify:artist:1v7B6ZWa7QRQS3knn3Jvf4"

[[instructions]]
    type = "artist_tracks"
    artist = "spotify:artist:1v7B6ZWa7QRQS3knn3Jvf4"
    fetch = -1
    select = 15

[[instructions]]
    type = "recommendations"
    artists = ["spotify:artist:7sEmXHrnEnX7PScoJAvSvo", "spotify:artist:5HrFJi08nNdu50d0AQVEi0", "spotify:artist:15fZ3hlvf6rcqHls6hZAbt"]

    min_instrumentalness = 0.5
    limit = 50
    pool_size = 100
    max_energy = 0.4

