clear_duplicates = true
region = 'US'
explicit = false

[audio_sort]
    method = 'traveling'
    chunks = 40
    random_offset = true
    attributes = ['energy', 'valence']

[upload]
    name = "Math but Chill"

[[instructions]]
    type = "recommendations"
    artists = ["spotify:artist:1v7B6ZWa7QRQS3knn3Jvf4", "spotify:artist:1v7B6ZWa7QRQS3knn3Jvf4"]

    max_speechiness = 0.3
    limit = 50
    max_energy = 0.6
    min_acousticness = 0.5

[[instructions]]
    type = "artist_top"
    artist = "spotify:artist:1v7B6ZWa7QRQS3knn3Jvf4"

[[instructions]]
    type = "artist_top"
    artist = "spotify:artist:1v7B6ZWa7QRQS3knn3Jvf4"

[[instructions]]
    type = "artist_tracks"
    artist = "spotify:artist:1v7B6ZWa7QRQS3knn3Jvf4"
    fetch = -1
    select = 15

[[instructions]]
    type = "recommendations"
    artists = ["fox capture plan", "PRIMITIVE ART ORCHESTRA", "SANOVA"]

    max_speechiness = 0.3
    limit = 50
    max_energy = 0.4

