name = "Peace"
daily = true

[[instructions]]
    type = "playlist"
    name = "Saved: Peace"

[[instructions]]
    # Gets recommendations for specific artists/songs
    # All this stuff is supported https://developer.spotify.com/documentation/web-api/reference/#/operations/get-recommendations
    type = "recommendations"
    artists = ["fox capture plan", "PRIMITIVE ART ORCHESTRA"]

    # You can fine tune exactly what you want
    max_speechiness = 0.2
    limit = 30
    max_energy = 0.3

[[instructions]]
    # Gets recommendations for specific artists/songs
    # All this stuff is supported https://developer.spotify.com/documentation/web-api/reference/#/operations/get-recommendations
    type = "recommendations"
    artists = ["SANOVA"]

    # You can fine tune exactly what you want
    max_speechiness = 0.2
    limit = 30
    max_energy = 0.3

[[instructions]]
    # You can also add genres https://developer.spotify.com/console/get-available-genre-seeds/
    type = "recommendations"
    artists = ["insaneintherainmusic"]
    max_speechiness = 0.1
    limit = 30
    max_energy = 0.3

[[instructions]]
    # Clears tracks before a specific date. In my case I want more modern songs. Especially modern jazz.
    type = 'clear_before'
    max_date = '1985-01-01'

[[instructions]]
    # You can also add genres https://developer.spotify.com/console/get-available-genre-seeds/
    type = "recommendations"
    tracks = ["Rest by Pheeno"]
    max_speechiness = 0.1
    limit = 30
    max_energy = 0.3

[[instructions]]
    # You can also add genres https://developer.spotify.com/console/get-available-genre-seeds/
    type = "recommendations"
    artists = ["All That Jazz"]
    tracks = ["めぐる季節"]
    max_speechiness = 0.1
    limit = 30
    max_energy = 0.3

[[instructions]]
    # You can also add genres https://developer.spotify.com/console/get-available-genre-seeds/
    type = "recommendations"
    artists = ["Siena Wind Orchestra"]
    tracks = ["アシタカとサン - Piano Solo Feature"]
    max_speechiness = 0.1
    limit = 30
    max_energy = 0.3

[[instructions]]
    # Clears duplicate tracks
    type = 'clear_duplicates'
