clear_duplicates = true
region = 'US'
explicit = false

random = true
trim = 75

[upload]
    name = "Peace"

[[instructions]]
    type = "playlist_tracks"
    name = "Saved: Peace"

[[instructions]]
    type = "playlist_tracks"
    name = "spotify:playlist:1d2zoGmfQPuxptnd8JBayK"
    sample = 30

[[instructions]]
    # Gets recommendations for specific artists/songs
    # All this stuff is supported https://developer.spotify.com/documentation/web-api/reference/#/operations/get-recommendations
    type = "recommendations"
    artists = ["fox capture plan", "PRIMITIVE ART ORCHESTRA"]

    # You can fine tune exactly what you want
    min_instrumentalness = 0.5
    limit = 30
    pool_size = 60
    max_energy = 0.3

[[instructions]]
    # Gets recommendations for specific artists/songs
    # All this stuff is supported https://developer.spotify.com/documentation/web-api/reference/#/operations/get-recommendations
    type = "recommendations"
    artists = ["SANOVA"]

    # You can fine tune exactly what you want
    min_instrumentalness = 0.5
    limit = 30
    pool_size = 60
    max_energy = 0.3

[[instructions]]
    # You can also add genres https://developer.spotify.com/console/get-available-genre-seeds/
    type = "recommendations"
    artists = ["insaneintherainmusic"]
    max_speechiness = 0.1
    limit = 30
    pool_size = 60
    max_energy = 0.3

[[instructions]]
    # You can also add genres https://developer.spotify.com/console/get-available-genre-seeds/
    type = "recommendations"
    artists = ["All That Jazz"]
    tracks = ["めぐる季節"]
    min_instrumentalness = 0.7
    pool_size = 60
    limit = 30
    max_energy = 0.3

[[instructions]]
    # You can also add genres https://developer.spotify.com/console/get-available-genre-seeds/
    type = "recommendations"
    artists = ["ichika", "spotify:artist:1v7B6ZWa7QRQS3knn3Jvf4"]
    min_instrumentalness = 0.7
    pool_size = 60
    limit = 30
    max_energy = 0.3

[[instructions]]
    # You can also add genres https://developer.spotify.com/console/get-available-genre-seeds/
    type = "recommendations"
    artists = ["Siena Wind Orchestra"]
    tracks = ["アシタカとサン - Piano Solo Feature"]
    min_instrumentalness = 0.6
    pool_size = 60
    limit = 30
    max_energy = 0.3
