clear_duplicates = true
region = 'US'

[audio_sort]
    method = 'traveling'

[upload]
    name = "Bops with Recs (Bopping)"

[energy]
    lower = 0.5
    upper = 1

[danceability]
    lower = 0.5
    upper = 1

[[instructions]]
    type = "playlist_tracks"
    name = "spotify:playlist:09XtrnnCzAKqOvsqDderH0"