clear_duplicates = true
region = 'US'

[audio_sort]
    method = 'traveling'

[upload]
    name = 'Power of Anime'

[[instructions]]
    type = "playlist_tracks"
    name = "spotify:playlist:73AyL1WxoRo8OI6glrZq9J"
