name: Update
on:
  # 8pm UTC is in the middle of the night
  schedule: [{cron: "0 8 * * *"}]
  # Let it be manually triggered
  workflow_dispatch:
jobs:
  update-playlists:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' # install the python needed
      - name: python requirements
        run: |
          pip install -r requirements.txt
      - name: execute python script
        run: |
          python main.py -a -s
        env:
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          redirect_uri: ${{ secrets.REDIRECT_URI }}
          saved_token: ${{ secrets.SAVED_TOKEN }}
